export const PROJECT_CONFIG = {
  ERROR_TYPES: {
    MISSING_PROJECT_CONFIG: 'MISSING_PROJECT_CONFIG',
    UNRECOGNIZED_ERROR: 'UNRECOGNIZED_ERROR',
    NOTIFICATION_SERVICE_ERROR: 'NOTIFICATION_SERVICE_ERROR',
    BIGQUERY_REQUEST_ERROR: 'BIGQUERY_REQUEST_ERROR',
  },
} as const
